import { createFileRoute } from "@tanstack/react-router";
import type {} from "@tanstack/react-start";

const BASE_URL = "https://conflictdash.lovable.app";
const LAST_UPDATED = "2026-07-31";

export const Route = createFileRoute("/sitemap.xml")({
  server: {
    handlers: {
      GET: async () => {
        const xml = [
          `<?xml version="1.0" encoding="UTF-8"?>`,
          `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`,
          `  <url>`,
          `    <loc>${BASE_URL}/</loc>`,
          `    <lastmod>${LAST_UPDATED}</lastmod>`,
          `    <changefreq>daily</changefreq>`,
          `    <priority>1.0</priority>`,
          `  </url>`,
          `  <url>`,
          `    <loc>${BASE_URL}/background/strait-of-hormuz</loc>`,
          `    <changefreq>monthly</changefreq>`,
          `    <priority>0.7</priority>`,
          `  </url>`,
          `  <url>`,
          `    <loc>${BASE_URL}/background/hezbollah-capabilities</loc>`,
          `    <changefreq>monthly</changefreq>`,
          `    <priority>0.7</priority>`,
          `  </url>`,
          `  <url>`,
          `    <loc>${BASE_URL}/background/world-war-3-risk</loc>`,
          `    <changefreq>weekly</changefreq>`,
          `    <priority>0.8</priority>`,
          `  </url>`,
          `  <url>`,
          `    <loc>${BASE_URL}/background/russian-casualties-ukraine</loc>`,
          `    <lastmod>${LAST_UPDATED}</lastmod>`,
          `    <changefreq>weekly</changefreq>`,
          `    <priority>0.8</priority>`,
          `  </url>`,
          `  <url>`,
          `    <loc>${BASE_URL}/background/will-china-invade-taiwan</loc>`,
          `    <lastmod>${LAST_UPDATED}</lastmod>`,
          `    <changefreq>weekly</changefreq>`,
          `    <priority>0.8</priority>`,
          `  </url>`,
          `  <url>`,
          `    <loc>${BASE_URL}/background/nuclear-weapons-by-country</loc>`,
          `    <lastmod>${LAST_UPDATED}</lastmod>`,
          `    <changefreq>monthly</changefreq>`,
          `    <priority>0.7</priority>`,
          `  </url>`,
          `  <url>`,
          `    <loc>${BASE_URL}/background/why-sudan-is-at-war</loc>`,
          `    <lastmod>${LAST_UPDATED}</lastmod>`,
          `    <changefreq>weekly</changefreq>`,
          `    <priority>0.8</priority>`,
          `  </url>`,
          `  <url>`,
          `    <loc>${BASE_URL}/background/pakistan-afghanistan-war-explained</loc>`,
          `    <lastmod>${LAST_UPDATED}</lastmod>`,
          `    <changefreq>weekly</changefreq>`,
          `    <priority>0.8</priority>`,
          `  </url>`,
          `  <url>`,
          `    <loc>${BASE_URL}/background/will-india-pakistan-go-to-war-again</loc>`,
          `    <lastmod>${LAST_UPDATED}</lastmod>`,
          `    <changefreq>weekly</changefreq>`,
          `    <priority>0.8</priority>`,
          `  </url>`,
          `  <url>`,
          `    <loc>${BASE_URL}/background/is-the-us-at-war</loc>`,
          `    <lastmod>${LAST_UPDATED}</lastmod>`,
          `    <changefreq>weekly</changefreq>`,
          `    <priority>0.8</priority>`,
          `  </url>`,
          `  <url>`,
          `    <loc>${BASE_URL}/deep-dive/ukraine</loc>`,
          `    <lastmod>${LAST_UPDATED}</lastmod>`,
          `    <changefreq>daily</changefreq>`,
          `    <priority>0.9</priority>`,
          `  </url>`,
          `  <url>`,
          `    <loc>${BASE_URL}/deep-dive/dronewar</loc>`,
          `    <lastmod>${LAST_UPDATED}</lastmod>`,
          `    <changefreq>daily</changefreq>`,
          `    <priority>0.8</priority>`,
          `  </url>`,
          `  <url>`,
          `    <loc>${BASE_URL}/deep-dive/usmil</loc>`,
          `    <lastmod>${LAST_UPDATED}</lastmod>`,
          `    <changefreq>daily</changefreq>`,
          `    <priority>0.8</priority>`,
          `  </url>`,
          `  <url>`,
          `    <loc>${BASE_URL}/deep-dive/iran</loc>`,
          `    <lastmod>${LAST_UPDATED}</lastmod>`,
          `    <changefreq>daily</changefreq>`,
          `    <priority>0.9</priority>`,
          `  </url>`,
          `  <url>`,
          `    <loc>${BASE_URL}/deep-dive/gaza</loc>`,
          `    <lastmod>${LAST_UPDATED}</lastmod>`,
          `    <changefreq>daily</changefreq>`,
          `    <priority>0.9</priority>`,
          `  </url>`,
          `  <url>`,
          `    <loc>${BASE_URL}/deep-dive/scs</loc>`,
          `    <lastmod>${LAST_UPDATED}</lastmod>`,
          `    <changefreq>daily</changefreq>`,
          `    <priority>0.8</priority>`,
          `  </url>`,
          `  <url>`,
          `    <loc>${BASE_URL}/deep-dive/venezuela</loc>`,
          `    <lastmod>${LAST_UPDATED}</lastmod>`,
          `    <changefreq>daily</changefreq>`,
          `    <priority>0.8</priority>`,
          `  </url>`,
          `  <url>`,
          `    <loc>${BASE_URL}/deep-dive/africa</loc>`,
          `    <lastmod>${LAST_UPDATED}</lastmod>`,
          `    <changefreq>daily</changefreq>`,
          `    <priority>0.8</priority>`,
          `  </url>`,
          `  <url>`,
          `    <loc>${BASE_URL}/deep-dive/southasia</loc>`,
          `    <lastmod>${LAST_UPDATED}</lastmod>`,
          `    <changefreq>daily</changefreq>`,
          `    <priority>0.8</priority>`,
          `  </url>`,
          `</urlset>`,
        ].join("\n");

        return new Response(xml, {
          headers: {
            "Content-Type": "application/xml",
            "Cache-Control": "public, max-age=3600",
          },
        });
      },
    },
  },
});
